name: squadron
description: Multithreading and worker thread pool for Dart / Flutter, to offload CPU-bound and heavy I/O tasks to Isolate or Web Worker threads.
version: 5.0.0
homepage: https://github.com/d-markey/squadron
repository: https://github.com/d-markey/squadron

environment:
  sdk: '>=2.13.0 <4.0.0'

dependencies:
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.3
  build_web_compilers: ">=3.2.7 <5.0.0"
  coverage: ^1.6.3
  http: ^0.13.5
  js: ^0.6.7
  lints: ">=2.0.0 <3.0.0"
  test: ^1.24.2
