name: squadron
description: Multithreading and worker thread pool for Dart / Flutter, to offload CPU-bound and heavy I/O tasks to Isolate or Web Worker threads.
version: 6.1.4
repository: https://github.com/d-markey/squadron

environment:
  sdk: ^3.4.0

dependencies:
  cancelation_token: ^1.1.0
  logger: ^2.1.0
  web: ^1.0.0
  meta:
  using:

dev_dependencies:
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.10
  coverage: ^1.6.3
  js: ^0.7.1
  lints: ^4.0.0
  test: ^1.25.8
  path: ^1.9.1
  synchronize: ^1.1.1

topics:
  - concurrency
  - isolate
  - multithread
  - web-worker

funding:
  - https://github.com/sponsors/d-markey
